server.port=${SERVER_PORT:4001}
grpc.server.port=${GRPC_SERVER_PORT:9001}

# ===== OBSERVABILITY =====
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://tempo:4318/v1/traces}
logging.pattern.correlation=[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]